sources used for the data

- https://www.kaggle.com/datasets/shivamb/netflix-shows
- https://www.kaggle.com/datasets/shivamb/amazon-prime-movies-and-tv-shows
- https://www.kaggle.com/datasets/shivamb/disney-movies-and-tv-shows

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import os
import calendar
import cleaning

In [2]:
df_amazon = pd.read_csv("amazon_prime_titles.csv", encoding="latin1")
df_disney = pd.read_csv("disney_plus_titles.csv", encoding="latin1")
df_netflix = pd.read_csv("netflix_titles.csv", encoding="latin1")

In [3]:
df_disney

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...
...,...,...,...,...,...,...,...,...,...,...,...,...
1445,s1446,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom","June 4, 2021",2009,PG-13,108 min,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...
1446,s1447,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada","April 2, 2021",2009,PG,106 min,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...
1447,s1448,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States","December 18, 2020",2016,PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum..."
1448,s1449,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States","September 18, 2020",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...
1449,s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.

Renaming Columns so they are capitalised and have the names I prefer

In [4]:
df_amazon.rename(columns = {'type':'Content type', 'title':'Title', 'release_year':'Date of release', 'duration':'Duration', 'listed_in':'Genre'}, inplace = True)
df_disney.rename(columns = {'type':'Content type', 'title':'Title', 'release_year':'Date of release', 'duration':'Duration', 'listed_in':'Genre'}, inplace = True)
df_netflix.rename(columns = {'type':'Content type', 'title':'Title', 'release_year':'Date of release', 'duration':'Duration', 'listed_in':'Genre'}, inplace = True)

In [5]:
df_amazon

,show_id,Content type,Title,director,cast,country,date_added,Date of release,rating,Duration,Genre,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, BeyoncÃƒÂ©, Britne...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

Check for missing values to determine what should be removed or not

In [6]:
#I am going to remove the rating(well use the one from IMDB) , description, cast, country and all (types == Movie) since we will only be looking at series for this comparison 

#Amazon
df_amazon.columns
df_amazon.isna().sum()

#Disney
df_disney.columns
df_disney.isna().sum()

#Netflix
df_netflix.columns
df_netflix.isna().sum()

show_id               0
Content type          0
Title                 0
director           2634
cast                825
country             831
date_added           10
Date of release       0
rating                4
Duration              3
Genre                 0
description           0
dtype: int64

Dropping the Rating/Description/cast/country/show_id/date_added and the director as they are not relevant for the analysis

In [7]:
df_amazon = df_amazon.drop([S], axis = 1)
df_disney = df_disney.drop(['rating', 'description', 'Content type','cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)
df_netflix = df_netflix.drop(['rating', 'description', 'Content type','cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)

In [8]:
df_amazon

,Title,Date of release,Duration,Genre
0,The Grand Seduction,2014,113 min,"Comedy, Drama"
1,Take Care Good Night,2018,110 min,"Drama, International"
2,Secrets of Deception,2017,74 min,"Action, Drama, Suspense"
3,Pink: Staying True,2014,69 min,Documentary
4,Monster Maker,1989,45 min,"Drama, Fantasy"
...,...,...,...,...
9663,Pride Of The Bowery,1940,60 min,Comedy
9664,Planet Patrol,2018,4 Seasons,TV Shows
9665,Outpost,2008,90 min,Action
9666,Maradona: Blessed Dream,2021,1 Season,"Drama, Sports"
9667,Harry Brown,2010,103 min,"Action, Drama, Suspense"

In [9]:
"""cleaning.drop(df_amazon, ['rating', 'description', 'cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)
cleaning.drop(df_disney, ['rating', 'description', 'cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)
cleaning.drop(df_netflix, ['rating', 'description', 'cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)"""

"cleaning.drop(df_amazon, ['rating', 'description', 'cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)\ncleaning.drop(df_disney, ['rating', 'description', 'cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)\ncleaning.drop(df_netflix, ['rating', 'description', 'cast', 'country', 'show_id', 'date_added', 'director'], axis = 1)"

Content type needs to be lower cased to make it esier to match values in Content Type and Movie/Series

In [10]:
df_amazon['Title'] = df_amazon['Title'].str.lower()
df_disney['Title'] = df_disney['Title'].str.lower()
df_netflix['Title'] = df_netflix['Title'].str.lower()

In [11]:
df_amazon = df_amazon.set_index(['Title'])
df_disney = df_disney.set_index(['Title'])
df_netflix = df_netflix.set_index(['Title'])

Setting the index of the dataframe to Title

In [12]:
"""cleaning.set_index(df_amazon, "Title")
cleaning.set_index(df_disney, "Title")
cleaning.set_index(df_netflix, "Title")"""

'cleaning.set_index(df_amazon, "Title")\ncleaning.set_index(df_disney, "Title")\ncleaning.set_index(df_netflix, "Title")'

In [13]:
df_amazon

                         Date of release   Duration                    Genre
Title
the grand seduction                 2014    113 min            Comedy, Drama
take care good night                2018    110 min     Drama, International
secrets of deception                2017     74 min  Action, Drama, Suspense
pink: staying true                  2014     69 min              Documentary
monster maker                       1989     45 min           Drama, Fantasy
...                                  ...        ...                      ...
pride of the bowery                 1940     60 min                   Comedy
planet patrol                       2018  4 Seasons                 TV Shows
outpost                             2008     90 min                   Action
maradona: blessed dream             2021   1 Season            Drama, Sports
harry brown                         2010    103 min  Action, Drama, Suspense

[9668 rows x 3 columns]

Saving csv files

Saved only the Genre for the match since "Title" is already assigned as the index and "content type" is not always correct in the database. The data base from IMDB does have this well documented. 

If not the title is printed twice in the merged dataframe

In [14]:
"""cleaning.reindex(df_amazon,'Genre')
cleaning.reindex(df_disney,'Genre')
cleaning.reindex(df_netflix,'Genre')"""

"cleaning.reindex(df_amazon,'Genre')\ncleaning.reindex(df_disney,'Genre')\ncleaning.reindex(df_netflix,'Genre')"

In [15]:
"""df_amazon = df_amazon.reindex(columns = ['Genre'])
df_disney = df_disney.reindex(columns = ['Genre'])
df_netflix = df_netflix.reindex(columns = ['Genre'])
"""

"df_amazon = df_amazon.reindex(columns = ['Genre'])\ndf_disney = df_disney.reindex(columns = ['Genre'])\ndf_netflix = df_netflix.reindex(columns = ['Genre'])\n"

Saving the new dataframes so they can be important to the next file and compared

In [16]:
df_amazon.to_csv("Amazon_merge.csv", index=True)
df_disney.to_csv("Disney_merge.csv", index=True)
df_netflix.to_csv("Netflix_merge.csv", index=True)

In [17]:
df_amazon

                         Date of release   Duration                    Genre
Title
the grand seduction                 2014    113 min            Comedy, Drama
take care good night                2018    110 min     Drama, International
secrets of deception                2017     74 min  Action, Drama, Suspense
pink: staying true                  2014     69 min              Documentary
monster maker                       1989     45 min           Drama, Fantasy
...                                  ...        ...                      ...
pride of the bowery                 1940     60 min                   Comedy
planet patrol                       2018  4 Seasons                 TV Shows
outpost                             2008     90 min                   Action
maradona: blessed dream             2021   1 Season            Drama, Sports
harry brown                         2010    103 min  Action, Drama, Suspense

[9668 rows x 3 columns]